# Generated by Django 4.1 on 2022-08-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="data_joined", new_name="date_joined",
        ),
    ]
